directories:
  output: eye
  buildResources: build
appId: com.gemini.app
productName: تطبيق فحص النظر الذكي
files:
  - filter:
      - dist/**/*
      - main.cjs
      - preload.js
      - activation.html
      - license.js
      - storage.js
      - splash.html
      - server
      - serviceAccountKey.json
      - package.json
win:
  target: nsis
  icon: public/100.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 42.0.1
